NaverCloudPlatform/ncloud-sdk-go

Makefile, common/parseErrorResponse.go, oauth/oauth_test.go, sdk/createBlockStorageInstance.go, sdk/createLoginKey.go, sdk/createPublicIpInstance.go, sdk/createServerImage.go, sdk/createServerInstances.go, sdk/deleteBlockStorageInstances.go, sdk/deleteLoginKey.go, sdk/deletePublicIpInstances.go, sdk/disassociatePublicIpFromServerInstance.go, sdk/getAccessControlGroupList.go, sdk/getAccessControlRuleList.go, sdk/getBlockStorageInstanceList.go, sdk/getLoginKeyList.go, sdk/getMemberServerImagesList.go, sdk/getPublicIpInstanceList.go, sdk/getRegionList.go, sdk/getRootPassword.go, sdk/getServerImageProductList.go, sdk/getServerInstanceList.go, sdk/getServerProductList.go, sdk/getZoneList.go, sdk/stopServerInstances.go, sdk/terminateServerInstances.go
- use gofmt
- fix error message
=> Fix errormessage

sdk/createBlockStorageInstance.go, sdk/createBlockStorageInstance_test.go, sdk/model.go
resolve #10 
- Add BlockStorageType
=> Add BlockStorageType

sdk/model.go, sdk/rebootServerInstances.go, sdk/rebootServerInstances_test.go
add rebootServerInstances API to sdk
=> add rebootServerInstances API to sdk

sdk/associatePublicIpWithServerInstance.go, sdk/associatePublicIpWithServerInstance_test.go, sdk/model.go, sdk/startServerInstances.go, sdk/startServerInstances_test.go
Adding the API to start servers..
=> startServerInstances and associatePublicIpWithServerInstance

sdk/changeServerInstanceSpec.go, sdk/changeServerInstancesSpec_test.go, sdk/model.go
add ChangeServerInstanceSpec API to sdk
=> add ChangeServerInstanceSpec

common/zone.go, sdk/createPublicIpInstance.go, sdk/createPublicIpInstance_test.go, sdk/getBlockStorageInstanceList.go, sdk/getBlockStorageInstanceList_test.go, sdk/getPublicIpInstanceList.go, sdk/getPublicIpInstanceList_test.go, sdk/getServerInstanceList.go, sdk/getServerInstanceList_test.go, sdk/model.go
resolve #16 
- Add Zone request/ response parameters
=> Add zone parameters

sdk/addPortForwardingRules.go, sdk/addPortForwardingRules_test.go, sdk/deletePortForwardingRules.go, sdk/deletePortForwardingRules_test.go, sdk/getPortForwardingList_test.go, sdk/getPortForwardingRuleList.go, sdk/model.go
add PortForwarding APIs (add/delete/get)
=> add PortForwarding APIs (add/delete/get)

sdk/createNasVolumeInstance.go, sdk/createNasVolumeInstance_test.go, sdk/model.go, sdk/validators.go
resolve #19 implement createNasVolumeInstance
=> implement createNasVolumeInstance

sdk/deleteNasVolumeInstance.go, sdk/deleteNasVolumeInstance_test.go
=> implement deleteNasVolumeInstance

sdk/createServerInstances.go, sdk/getAccessControlGroupList.go, sdk/getAccessControlGroupList_test.go, sdk/getPublicIpInstanceList.go, sdk/model.go, sdk/validators.go
golang 에서는 bool 값을 입력안해도 기본 false 로 판단하기 때문에, bool type 을  request 인자로 쓰기 어려움.
=> Fix request bool type

sdk/createLoadBalancerInstance.go, sdk/createLoadBalancerInstance_test.go, sdk/deleteNasVolumeInstance.go, sdk/deletePortForwardingRules.go, sdk/getNasVolumeInstanceList.go, sdk/model.go, sdk/sdk_suite_test.go
=> #24 create load balancer instance

sdk/getNasVolumeInstanceList.go
getNasVolumeInstanceList Set the VolumeAllotmentProtocolTypeCode parameter to optional
=> getNasVolumeInstanceList Set the VolumeAllotmentProtocolTypeCode parameter to optional

sdk/deleteLoadBalancerInstances.go, sdk/deleteLoadBalancerInstances_test.go, sdk/model.go, sdk/sdk_suite_test.go
resolve #26 
- Implement delete load balnacer instances
=> implement delete load balnacer instances

sdk/changeLoadBalancerInstanceConfiguration.go, sdk/changeLoadBalancerInstanceConfiguration_test.go, sdk/getLoadBalancerInstanceList.go, sdk/model.go
=> implement  ChangeLoadBalancerInstanceConfiguration

sdk/getLoadBalancerSslCertificateList.go, sdk/getLoadBalancerSslCertificateList_test.go, sdk/model.go
=> implement GetLoadBalancerSslCertificateList

sdk/addLoadBalancerSslCertificate.go, sdk/addLoadBalancerSslCertificate_test.go, sdk/model.go
=> #28 add load balancer ssl certificate

sdk/addLoadBalancerSslCertificate.go, sdk/addLoadBalancerSslCertificate_test.go, sdk/deleteLoadBalancerSslCertificate.go, sdk/deleteLoadBalancerSslCertificate_test.go, sdk/model.go
=> #29 delete load balancer ssl certificate

sdk/getLoadBalancerTargetServerInstanceList.go, sdk/getLoadBalancerTargetServerInstanceList_test.go, sdk/model.go
=> implement getLoadBalancerTargetServerInstanceList

sdk/getLoadBalancedServerInstanceList.go, sdk/getLoadBalancedServerInstanceList_test.go, sdk/getLoadBalancerTargetServerInstanceList.go, sdk/getLoadBalancerTargetServerInstanceList_test.go, sdk/model.go
=> #31 get load balanced server instance list

sdk/changeLoadBalancedServerInstances.go, sdk/changeLoadBalancedServerInstances_test.go, sdk/model.go
=> #32 implement changeLoadBalancedServerInstances

sdk/model.go, sdk/setNasVolumeAccessControl.go, sdk/setNasVolumeAccessControl_test.go
=> #57 set nas volume access control

sdk/addNasVolumeAccessControl.go, sdk/addNasVolumeAccessControl_test.go, sdk/model.go
=> implement AddNasVolumeAccessControl

sdk/deleteNasVolumeAccessControl.go, sdk/deleteNasVolumeAccessControl_test.go
=> implement RemoveNasVolumeAccessControl

sdk/createServerInstances.go, sdk/createServerInstances_test.go, sdk/getServerImageProductList.go, sdk/getServerInstanceList.go, sdk/getServerProductList.go, sdk/model.go
=> add additional parameters

sdk/addLoadBalancerSslCertificate.go, sdk/attachBlockStorageInstance.go, sdk/attachBlockStorageInstance_test.go, sdk/deleteBlockStorageInstances.go, sdk/deleteLoadBalancerInstances.go, sdk/deleteLoadBalancerInstances_test.go, sdk/deleteLoadBalancerSslCertificate.go, sdk/deleteNasVolumeAccessControl.go, sdk/deletePortForwardingRules.go, sdk/detachBlockStorageInstances.go, sdk/getAccessControlRuleList.go, sdk/getLoadBalancedServerInstanceList.go, sdk/getLoadBalancedServerInstanceList_test.go, sdk/getServerProductList.go, sdk/model.go, sdk/rebootServerInstances.go, sdk/setNasVolumeAccessControl.go, sdk/startServerInstances.go, sdk/stopServerInstances.go, sdk/terminateServerInstances.go
=> implement attach block storage instance

sdk/createBlockStorageSnapshotInstance.go, sdk/createBlockStorageSnapshotInstance_test.go, sdk/deleteBlockStorageSnapshotInstances.go, sdk/deleteBlockStorageSnapshotInstances_test.go, sdk/getBlockStorageSnapshotInstanceList.go, sdk/getBlockStorageSnapshotInstanceList_test.go, sdk/model.go
=> #70 block storage snapshot api

sdk/getPortForwardingRuleList_test.go, sdk/model.go
=> fix model to add portForwardingpublicIP

sdk/createServerInstances.go
fix #77 
IsProtectServerTermination => isProtectServerTermination
=> fix typo - CreateServerInstances IsProtectServerTermination

sdk/getPortForwardingRuleList_test.go, sdk/model.go
=> add zone info to GetPortForwardingRuleList

sdk/getNasVolumeInstanceList.go
`IsEventConfiguration` => `IsSnapshotConfiguration`
=> fix nas volume parameter
